#!/bin/bash
if [ $# -eq 0 ] ; then
  echo
  echo "Usage: rtc2git_images COMMAND [COMMAND...]"
  echo
  echo "Commands:"
  echo "    build     Build rtc2git images for all existing base images"
  echo "    push      Pushes the generated images"
  echo
  exit 1
fi 

build=false
push=false

for ARG in $* ; do
  case $ARG in
    "build" )
      build=true 
      ;;
    "push" )
      push=true 
      ;;
  esac 
done

if $build; then
  mkdir build
  cp -r plugins/ build/
  for RTC_VERSION in $(sudo docker images --format "{{.Tag}}" docker.io/rtcto/rtc) ; do
      echo "Building rtc2git image for version $RTC_VERSION"
      sed -e "s/FROM docker\.io\/rtcto\/rtc:.*/FROM docker.io\/rtcto\/rtc:$RTC_VERSION/" Dockerfile >build/Dockerfile
      sudo docker build -t docker.io/rtcto/rtc2git:$RTC_VERSION build 
  done
  rm -rf build
fi

if $push ; then
  for RTC_VERSION in $(sudo docker images --format "{{.Tag}}" docker.io/rtcto/rtc2git) ; do
    echo "Pushing version $RTC_VERSION"
    sudo docker push docker.io/rtcto/rtc2git:$RTC_VERSION
  done
fi
